name: CodeCov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  run:
    rruns-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: "3.12"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run unittests with coverage
      run: |
        coverage run -m unittest discover

    - name: Generate coverage report
      run: coverage xml

    - name: Show coverage file content
      run: cat ./coverage.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
